language: rust
dist: trusty
osx_image: xcode7.3
rust:
   - stable
addons:
  apt:
    packages:
      - libglpk-dev
script: |
   cargo build --verbose &&
   cargo test --verbose &&
   cargo run --example main
