language: rust
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode7.3
rust:
   - stable
addons:
  apt:
    packages:
      - libglpk-dev
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glpk; fi
script: |
   cargo build --verbose &&
   cargo test --verbose &&
   cargo run --example main
