language: rust
matrix:
  include:
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      dist: trusty
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
      addons:
        apt:
          packages:
            - libglpk-dev
before install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glpk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew --prefix glpk; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then find /usr/local; fi
script: |
   cargo build --verbose &&
   cargo test --verbose &&
   cargo run --example main
